### PR TITLE
Fix matching for '@array@||@null@'

### LINKED ISSUE #471: Not able to match `@null@||@array@` (again)
There is already a closed issue that reports my same exact problem:

- https://github.com/coduo/php-matcher/issues/212

My array structure is almost this:

```json
{
    "@context": "\/api\/contexts\/MyClass",
    "@id": "\/api\/myclasses\/2",
    "hydra:member": [
        {
            "id": 1,
            "my_key": {
                "key1": "EUR",
                "key2": 0.22
            }
        }
    ]
}
```

`my_key` can also be `null`:

```json
{
    "@context": "\/api\/contexts\/MyClass",
    "@id": "\/api\/myclasses\/2",
    "hydra:member": [
        {
            "id": 1,
            "my_key": null
        }
    ]
}
```

So, to validate this structure, I use this pattern:

```
[
                '@context'         => '/{app_api_entrypoint}/contexts/' . StringHelper::getClassBaseName(Item::class),
                '@id'              => '/{app_api_entrypoint}{api_endpoint}',
                '@type'            => 'hydra:Collection',
                'hydra:totalItems' => AbstractItemsFixture::COUNT_TOTAL_IN_ACCOUNT,
                'hydra:member'     => [
                    [
                        '@id' => '@string@',
                        'my_key' => '@array@ || @null@',
...
```

This validation does not pass:

> Failed asserting that Value "Array(2)" does not match pattern "[hydra:member][0]" at path: "[hydra:member][0][my_key]".

Am I doing it wrong or is it actually a bug?

### PR DESCRIPTION
**Pull request by GeLoLabs**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
    <li>Fix #471 </li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

This PR fixes #471 by making aware the "OrMatcher" about the "ArrayMatcher".

### CODE REVIEW

File: src/Factory/MatcherFactory.php [hunk 1]
```diff
@@ -49,21 +49,23 @@ private function buildMatchers(Parser $parser, Backtrace $backtrace) : Matcher\C
...
-        $orMatcher = new Matcher\OrMatcher($backtrace, $scalarMatchers);
-
-        return new Matcher\ArrayMatcher(
+        $arrayMatcher = new Matcher\ArrayMatcher(
             new Matcher\ChainMatcher(
                 'array',
                 $backtrace,
                 [
-                    $orMatcher,
+                    new Matcher\OrMatcher($backtrace, $orMatchers = clone $scalarMatchers),
```
Comment (norberttech) [inline src/Factory/MatcherFactory.php:57]: have you tried it without a clone?

Comment (GeLoLabs) [reply src/Factory/MatcherFactory.php:57]: Deleting the clone works but I added it here for a specific reason. Since the factory describes the following matcher priorities:

```
// Matchers are registered in order of matching
// 1) all scalars
// 2) json/xml
// 3) array
// 4) or "||"
// 5) full text
```

I have decided to clone the scalair matchers in order to keep theses priorities on the main matcher.

Comment (norberttech) [reply src/Factory/MatcherFactory.php:57]: and without clone that order is changed?

**Comment by norberttech** [comment]
in order to fix that static analysis error run <code>composer cs:php:fix</code>

**Review by norberttech — CHANGES_REQUESTED** [review]
So here are two things that need to be clarified/added before this can be merged: 

1) I would love to understand why that cloning is necessary and what are the consequences of not using clone
2) There needs to be some tests added that would fail before this fix is implemented

**Comment by GeLoLabs** [comment]
@norberttech I have added a test covering this fix. 

For the cloning part, I keep BC strictly according to the documented matcher priorites, if you prefer, I can drop it but the, I would also drop the registering of the original array matcher on the main matcher chain since it would become part of the scalar matcher chain.

By the way, if I don't clone it, the test becomes broken.

**Review by norberttech — APPROVED** [review]

**Comment by norberttech** [comment]
> By the way, if I don't clone it, the test becomes broken.

This is what I wanted to know, thanks!
